### ISSUE TITLE
systemtap to be removed

### ISSUE THREAD

**Issue by junaruga** [fedora-modularity/f27-content-tracking#25]
Last time I requested systemtap module because ruby module depends on it.
But the ruby module could be built without the systemtap module, as I removed the systemtap build dependency in rpms/ruby by conditional macro.

So, we may be able to remove the systemtap module from targeted.
https://github.com/fedora-modularity/f27-content-tracking

**Comment by TomasTomecek** [comment]
I believe that a bunch of other modules need systemtap by default.

**Comment by junaruga** [comment]
OK I would close this ticket.
