### ISSUE TITLE
Module Guidelines and Process Approved 

### ISSUE THREAD

**Issue by langdon** [fedora-modularity/f27-content-tracking#3]
We need the process and guidelines approved to allow people to create modules in Fedora. 

* [Process](https://fedoraproject.org/wiki/Module:Review_Process)
* [Guidelines](https://fedoraproject.org/wiki/Module:Guidelines)
* [FESCo Approval ticket](https://pagure.io/fesco/issue/1763)

**Comment by alexxa** [comment]
@whitel is it still valid? Is there a relevant Jira ticket beside this one synced to Jira? Who is an assigner?
