### ISSUE TITLE
Arbitrary Branching is deployed

### ISSUE THREAD

**Issue by langdon** [fedora-modularity/f27-content-tracking#4]
We need the arbitrary branching to make real changes to modules.

* [Fedora Change](https://fedoraproject.org/wiki/Changes/ArbitraryBranching)
* Tracker bug: [#1458665](https://bugzilla.redhat.com/show_bug.cgi?id=1458665)

**Comment by KarstenHopp** [comment]
Arbitrary Branching has deployed on src.fp.o and has already been used to build some modules from 'nonstandard' branches
